# nginx proxy address - http://172.17.0.1:59082

name: acme
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  server:
    image: knrdl/acme-ca-server:latest
    container_name: acme-server
    domainname: ${BASE_DOMAIN_NAME}
    hostname: ${BASE_HOST_NAME:-${HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      - EXTERNAL_URL=https://${BASE_HOST_NAME:-${HOSTNAME}}
      - ACME_TERMS_OF_SERVICE_URL=https://${BASE_HOST_NAME:-${HOSTNAME}}/terms
      - WEB_ENABLED=true
      - WEB_ENABLE_PUBLIC_LOG=true
      - 'WEB_APP_TITLE=${APP_ORG_NAME:-Acme} CA'
      - 'WEB_APP_DESCRIPTION=${APP_ORG_NAME:-Acme} server'
      - CA_ENABLED=true
      - CA_CRL_LIFETIME=7d
      - CA_CERT_LIFETIME=120d
      - MAIL_ENABLED=true
      - MAIL_HOST=${EMAIL_SERVER_HOST:-172.17.0.1}
      - MAIL_PORT=${EMAIL_SERVER_PORT:-25}
      - 'MAIL_SENDER=${EMAIL_SERVER_FROM_NAME}'
      - MAIL_ENCRYPTION=starttls
      - MAIL_WARN_BEFORE_CERT_EXPIRES=14d
      - MAIL_NOTIFY_WHEN_CERT_EXPIRED=true
      - MAIL_NOTIFY_ON_ACCOUNT_CREATION=true
      - CA_ENCRYPTION_KEY=${APP_SECRET_KEY:-7kpDGKZX551rWdEnviCpna0MnTnUieEH}
      - DB_DSN=postgresql://postgres:DkVwdvMKo9c1nf5wTGStzXYnSHRLiiIf@acme-db/postgres
    ports:
      - '172.17.0.1:59082:8080'
    volumes:
      - '/etc/ssl/CA/CasjaysDev/certs/ca.crt:/import/ca.pem:ro'
      - '/etc/ssl/CA/CasjaysDev/private/ca.key:/import/ca.key:ro'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - acme

  db:
    image: postgres:15-alpine
    container_name: acme-db
    domainname: ${BASE_DOMAIN_NAME}
    hostname: acme-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      - POSTGRES_PASSWORD=DkVwdvMKo9c1nf5wTGStzXYnSHRLiiIf
    volumes:
      - '/var/lib/srv/${USER}/databases/postgresql/acme:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'runuser', '-u', 'postgres', '--', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - acme

networks:
  acme:
    name: acme
    external: false
